USE DOCKERIZED;
CREATE TABLE users(
   id INT AUTO_INCREMENT,
   name VARCHAR(50) NOT NULL,
   PRIMARY KEY(id)
);

CREATE TABLE posts(
   id INT AUTO_INCREMENT,
   title VARCHAR(50) NOT NULL,
   PRIMARY KEY(id)
);